In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor
#from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
data = {
    "mahalle": [
        "شهرک وحدت","بعثت","بعثت","بعثت","شهرک پارسیان",
        "شهرک ولیعصر","مدرس","شهرک فرهنگیان","شهرک دانش","هشتگرد قدیم",
        "شهرک ولیعصر","بعثت","شهرک راه آهن","شهرک وحدت","شهرک آرتیمان",
        "شهرک دانش","شهرک فرهنگیان","مدرس","بعثت","شهرک ولیعصر",
        "شهرک پارسیان","هشتگرد قدیم","شهرک وحدت","بعثت","شهرک ولیعصر",
        "مدرس","شهرک دانش","شهرک فرهنگیان","شهرک راه آهن","بعثت",
        "هشتگرد قدیم","شهرک ولیعصر","بعثت","شهرک آرتیمان","شهرک دانش",
        "شهرک وحدت","مدرس","شهرک فرهنگیان","شهرک پارسیان","بعثت",
        "شهرک ولیعصر","هشتگرد قدیم","شهرک دانش","مدرس","شهرک راه آهن",
        "بعثت","شهرک فرهنگیان","شهرک وحدت","شهرک آرتیمان","شهرک ولیعصر",
        "شهرک دانش","بعثت","مدرس","شهرک پارسیان","هشتگرد قدیم",
        "شهرک ولیعصر","شهرک فرهنگیان","شهرک راه آهن","بعثت","شهرک وحدت",
        "مدرس","شهرک دانش","شهرک آرتیمان","شهرک ولیعصر","بعثت",
        "هشتگرد قدیم","شهرک پارسیان","شهرک فرهنگیان","شهرک وحدت","مدرس",
        "شهرک راه آهن","بعثت","شهرک دانش","شهرک ولیعصر","شهرک آرتیمان",
        "هشتگرد قدیم","شهرک فرهنگیان","بعثت","مدرس","شهرک دانش",
        "شهرک وحدت","شهرک ولیعصر","شهرک پارسیان","بعثت","هشتگرد قدیم",
        "مدرس","شهرک فرهنگیان","شهرک دانش","شهرک راه آهن","شهرک ولیعصر",
        "بعثت","شهرک آرتیمان","شهرک وحدت","مدرس","شهرک دانش","شهرک وحدت","بعثت","بعثت","بعثت","شهرک پارسیان"
    ],

    "metraj": [
        115,130,140,100,70,85,120,75,110,95,
        105,90,125,80,65,145,70,100,120,150,
        85,110,75,135,95,125,100,80,105,115,
        90,140,70,100,130,85,110,75,95,120,
        105,65,150,90,115,100,80,125,70,135,
        110,85,120,75,105,145,90,100,130,80,
        115,70,140,95,125,85,100,75,110,150,
        90,120,105,80,135,65,115,100,145,85,
        110,70,125,95,150,80,105,130,75,115,
        90,140,100,85,120,70,135,95,110,145
    ],

    "tedad otagh": [
        3,2,2,2,1,2,3,2,2,2,
        2,2,3,2,1,3,1,2,3,3,
        2,2,2,3,2,3,2,2,2,2,
        2,3,1,2,3,2,2,1,2,3,
        2,1,3,2,2,2,2,3,1,3,
        2,2,3,1,2,3,2,2,3,2,
        2,1,3,2,3,2,2,1,2,3,
        2,2,2,2,3,1,2,2,3,2,
        2,1,3,2,3,2,2,3,1,2,
        2,3,2,2,3,1,3,2,2,3
    ],

    "tedad servis": [
        1,2,2,1,1,1,2,1,2,1,
        1,1,2,1,1,2,1,1,2,2,
        1,1,1,2,1,2,1,1,1,2,
        1,2,1,1,2,1,2,1,1,2,
        1,1,2,1,2,1,1,2,1,2,
        2,1,2,1,1,2,1,1,2,1,
        2,1,2,1,2,1,1,1,2,2,
        1,2,1,1,2,1,1,2,2,1,
        2,1,2,1,2,1,1,2,1,2,
        1,2,1,1,2,1,2,1,2,2
    ],

    "parking": [
        1,1,1,1,1,1,1,0,1,1,
        1,0,1,1,0,1,0,1,1,1,
        1,1,0,1,1,1,1,0,1,1,
        1,1,1,1,1,0,1,0,1,1,
        1,1,1,0,1,1,0,1,1,1,
        1,1,0,1,1,1,1,0,1,1,
        1,0,1,1,1,1,0,1,1,1,
        1,1,1,0,1,1,1,1,1,0,
        1,1,1,1,0,1,1,0,1,1,
        1,1,0,1,1,1,0,1,1,1
    ],

    "anbari": [
        1,1,1,0,1,1,1,0,1,1,
        1,1,1,1,0,1,0,1,1,1,
        1,0,1,1,1,1,1,0,1,1,
        1,1,0,1,1,0,1,1,1,1,
        1,1,1,0,1,1,0,1,1,1,
        1,0,1,1,1,1,0,1,1,1,
        1,1,1,0,1,1,1,0,1,1,
        0,1,1,1,1,0,1,1,1,0,
        1,1,0,1,1,1,0,1,1,1,
        1,0,1,1,1,1,0,1,1,1
    ],

    "asansor": [
        1,1,1,1,0,1,1,1,1,1,
        1,1,1,1,0,1,1,0,1,1,
        1,1,0,1,1,1,1,0,1,1,
        1,1,1,0,1,1,0,1,1,1,
        1,1,1,1,0,1,1,1,1,1,
        1,0,1,1,1,1,0,1,1,1,
        1,1,0,1,1,1,1,0,1,1,
        1,1,1,0,1,1,1,1,0,1,
        1,1,0,1,1,1,0,1,1,1,
        1,1,1,0,1,1,0,1,1,1
    ],

    "tabaghe": [
        3,2,2,3,1,2,4,3,2,1,
        3,2,4,2,3,5,1,3,2,4,
        1,2,3,2,4,3,2,1,4,3,
        2,5,1,3,4,2,3,1,4,2,
        3,2,5,1,3,2,4,3,1,4,
        2,3,5,2,4,3,1,2,4,5,
        2,1,3,4,2,5,1,3,4,2,
        3,2,4,1,5,2,3,4,2,1,
        4,2,3,5,1,2,4,3,2,5,
        1,4,2,3,5,1,4,2,3,5
    ],

    "balkon": [
        1,1,1,0,1,1,1,0,1,1,
        1,0,1,1,0,1,1,1,0,1,
        1,1,0,1,1,1,0,1,1,0,
        1,1,1,0,1,1,0,np.nan,1,1,
        0,1,1,1,1,0,1,1,0,1,
        1,1,np.nan,1,1,1,0,1,1,1,
        1,0,1,1,1,0,1,1,1,0,
        1,1,0,1,1,1,0,1,1,0,
        1,0,1,1,1,0,1,np.nan,0,1,
        1,1,0,1,1,1,0,1,0,1
    ],

    "kabinet": [
        1,1,1,0,np.nan,1,1,1,0,1,
        1,0,1,1,1,1,0,1,1,1,
        0,1,1,1,1,0,1,1,1,0,
        1,1,0,1,1,1,0,1,1,1,
        1,0,1,1,0,1,1,np.nan,0,1,
        1,1,0,1,1,0,1,1,1,1,
        1,0,np.nan,1,1,1,0,1,1,0,
        1,1,0,1,1,1,0,1,1,1,
        1,0,1,1,np.nan,1,1,1,0,1,
        1,1,0,1,1,1,0,1,0,1
    ],

    "sal sakht": [
        1403,1405,1396,1405,1394,1399,1402,1390,1398,1388,
        1401,1392,1400,1395,1387,1404,1391,1398,1401,1403,
        1395,1390,1402,1398,1404,1396,1405,1389,1397,1400,
        1393,1402,1386,1399,1404,1395,1401,1390,1398,1402,
        1403,1391,1405,1397,1394,1400,1388,1399,1392,1404,
        1405,1396,1401,1390,1398,1403,1391,1400,1405,1395,
        1402,1394,1405,1397,1401,1385,1404,1392,1399,1403,
        1390,1405,1396,1402,1389,1397,1404,1393,1401,1398,
        1405,1390,1402,1395,1404,1391,1399,1403,1397,1405,
        1392,1401,1396,1404,1390,1405,1393,1402,1398,1404
    ],

    "gheymat": [
        7450000000,8000000000,8150000000,6950000000,3350000000,
        5100000000,10200000000,2900000000,8750000000,6250000000,
        6500000000,4650000000,7850000000,4200000000,2700000000,
        12100000000,3100000000,7500000000,7800000000,11200000000,
        4100000000,7350000000,3850000000,9200000000,5900000000,
        8750000000,7900000000,3050000000,6100000000,7050000000,
        5150000000,10400000000,4200000000,3950000000,9800000000,
        4550000000,8200000000,2750000000,4600000000,8100000000,
        6800000000,5700000000,11900000000,5850000000,6500000000,
        7200000000,2950000000,5250000000,3150000000,9500000000,
        9100000000,5400000000,8900000000,3550000000,6900000000,
        6100000000,2700000000,5700000000,8250000000,4100000000,
        8450000000,10500000000,3650000000,5200000000,7200000000,
        6300000000,7450000000,2800000000,4300000000,8600000000,
        5400000000,6700000000,10800000000,5800000000,3300000000,
        6200000000,2850000000,7900000000,7600000000,9400000000,
        3900000000,4700000000,6800000000,8500000000,10800000000,
        3600000000,5900000000,4400000000,7300000000,7100000000,
        6100000000,8200000000,4600000000,9300000000,7000000000,
        3200000000,8000000000,5300000000,6800000000,11500000000
    ]
}
df = pd.DataFrame(data)
df

,mahalle,metraj,tedad otagh,tedad servis,parking,anbari,asansor,tabaghe,balkon,kabinet,sal sakht,gheymat
0,شهرک وحدت,115,3,1,1,1,1,3,1.0,1.0,1403,7450000000
1,بعثت,130,2,2,1,1,1,2,1.0,1.0,1405,8000000000
2,بعثت,140,2,2,1,1,1,2,1.0,1.0,1396,8150000000
3,بعثت,100,2,1,1,0,1,3,0.0,0.0,1405,6950000000
4,شهرک پارسیان,70,1,1,1,1,0,1,1.0,NaN,1394,3350000000
...,...,...,...,...,...,...,...,...,...,...,...,...
95,شهرک وحدت,70,1,1,1,1,1,1,1.0,1.0,1405,3200000000
96,بعثت,135,3,2,0,0,0,4,0.0,0.0,1393,8000000000
97,بعثت,95,2,1,1,1,1,2,1.0,1.0,1402,5300000000
98,بعثت,110,2,2,1,1,1,3,0.0,0.0,1398,6800000000
99,شهرک پارسیان,145,3,2,1,1,1,5,1.0,1.0,1404,11500000000

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mahalle       100 non-null    object
 1   metraj        100 non-null    int64
 2   tedad otagh   100 non-null    int64
 3   tedad servis  100 non-null    int64
 4   parking       100 non-null    int64
 5   anbari        100 non-null    int64
 6   asansor       100 non-null    int64
 7   tabaghe       100 non-null    int64
 8   balkon        97 non-null     float64
 9   kabinet       96 non-null     float64
 10  sal sakht     100 non-null    int64
 11  gheymat       100 non-null    int64
dtypes: float64(2), int64(9), object(1)
memory usage: 9.5+ KB

In [42]:
df.isnull().sum()

mahalle         0
metraj          0
tedad otagh     0
tedad servis    0
parking         0
anbari          0
asansor         0
tabaghe         0
balkon          3
kabinet         4
sal sakht       0
gheymat         0
dtype: int64

In [43]:
df.describe()

,metraj,tedad otagh,tedad servis,parking,anbari,asansor,tabaghe,balkon,kabinet,sal sakht,gheymat
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,97.000000,96.000000,100.000000,1.000000e+02
mean,104.550000,2.150000,1.420000,0.800000,0.79000,0.820000,2.780000,0.731959,0.750000,1397.880000,6.485500e+09
std,24.016987,0.641573,0.496045,0.402015,0.40936,0.386123,1.251908,0.445240,0.435286,5.505333,2.403798e+09
min,65.000000,1.000000,1.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,1385.000000,2.700000e+09
25%,85.000000,2.000000,1.000000,1.000000,1.00000,1.000000,2.000000,0.000000,0.750000,1393.750000,4.512500e+09
50%,102.500000,2.000000,1.000000,1.000000,1.00000,1.000000,3.000000,1.000000,1.000000,1398.500000,6.500000e+09
75%,121.250000,3.000000,2.000000,1.000000,1.00000,1.000000,4.000000,1.000000,1.000000,1403.000000,8.112500e+09
max,150.000000,3.000000,2.000000,1.000000,1.00000,1.000000,5.000000,1.000000,1.000000,1405.000000,1.210000e+10

In [44]:
df.describe(include="all")

,mahalle,metraj,tedad otagh,tedad servis,parking,anbari,asansor,tabaghe,balkon,kabinet,sal sakht,gheymat
count,100,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,97.000000,96.000000,100.000000,1.000000e+02
unique,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,بعثت,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,104.550000,2.150000,1.420000,0.800000,0.79000,0.820000,2.780000,0.731959,0.750000,1397.880000,6.485500e+09
std,NaN,24.016987,0.641573,0.496045,0.402015,0.40936,0.386123,1.251908,0.445240,0.435286,5.505333,2.403798e+09
min,NaN,65.000000,1.000000,1.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,1385.000000,2.700000e+09
25%,NaN,85.000000,2.000000,1.000000,1.000000,1.00000,1.000000,2.000000,0.000000,0.750000,1393.750000,4.512500e+09
50%,NaN,102.500000,2.000000,1.000000,1.000000,1.00000,1.000000,3.000000,1.000000,1.000000,1398.500000,6.500000e+09
75%,NaN,121.250000,3.000000,2.000000,1.000000,1.00000,1.000000,4.000000,1.000000,1.000000,1403.000000,8.112500e+09
max,NaN,150.000000,3.000000,2.000000,1.000000,1.00000,1.000000,5.000000,1.000000,1.000000,1405.000000,1.210000e+10

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.isnull().sum()

mahalle         0
metraj          0
tedad otagh     0
tedad servis    0
parking         0
anbari          0
asansor         0
tabaghe         0
balkon          3
kabinet         4
sal sakht       0
gheymat         0
dtype: int64

In [47]:
X=df.drop("gheymat",axis=1)
Y=df["gheymat"]

In [48]:
X =pd.get_dummies(
    X,
    columns=["mahalle"],
    dtype=int
)

X.head()

,metraj,tedad otagh,tedad servis,parking,anbari,asansor,tabaghe,balkon,kabinet,sal sakht,mahalle_بعثت,mahalle_شهرک آرتیمان,mahalle_شهرک دانش,mahalle_شهرک راه آهن,mahalle_شهرک فرهنگیان,mahalle_شهرک وحدت,mahalle_شهرک ولیعصر,mahalle_شهرک پارسیان,mahalle_مدرس,mahalle_هشتگرد قدیم
0,115,3,1,1,1,1,3,1.0,1.0,1403,0,0,0,0,0,1,0,0,0,0
1,130,2,2,1,1,1,2,1.0,1.0,1405,1,0,0,0,0,0,0,0,0,0
2,140,2,2,1,1,1,2,1.0,1.0,1396,1,0,0,0,0,0,0,0,0,0
3,100,2,1,1,0,1,3,0.0,0.0,1405,1,0,0,0,0,0,0,0,0,0
4,70,1,1,1,1,0,1,1.0,NaN,1394,0,0,0,0,0,0,0,1,0,0

In [49]:
X_train,X_test,Y_train,Y_test=train_test_split(
    X,Y,test_size=0.2,random_state=42)

In [50]:
from sklearn.preprocessing import StandardScaler
scaler_y = StandardScaler()
Y_train = scaler_y.fit_transform(Y_train.values.reshape(-1, 1)).ravel()
Y_test = scaler_y.transform(Y_test.values.reshape(-1, 1)).ravel()

In [51]:
imputer=SimpleImputer(strategy="median")
X_train=imputer.fit_transform(X_train)
X_test=imputer.transform(X_test)

In [52]:
print(X_train.dtypes)

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
model = LinearRegression()
scores = cross_val_score(model,X_train,Y_train,cv=5,
                         scoring="r2")
print("CV Scores:", scores)
print("Mean R²:", scores.mean())
model.fit(X_train,Y_train)
Y_pred_linear = model.predict(X_test)
mae2 = mean_absolute_error(Y_test, Y_pred_linear)
rmse2 = np.sqrt(mean_squared_error(Y_test, Y_pred_linear))
r22 = r2_score(Y_test, Y_pred_linear)
print("MAE:", mae2)
print("RMSE:", rmse2)
print("R²:", r22)

In [ ]:
model2=RandomForestRegressor(
    n_estimators=100,
    random_state=42)
scores = cross_val_score(model2,X_train,Y_train,cv=5,
                         scoring="r2")
print("CV Scores:", scores)
print("Mean R²:", scores.mean())

In [ ]:
param_grid = {
    "n_estimators": [50, 100,200],
    "max_depth": [None,5,15,20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [ 2,3]
}
grid_search=GridSearchCV(
    estimator=model2,
    param_grid=param_grid,
    cv=6,
    scoring="r2",
    n_jobs=-1
)
grid_search.fit(X_train,Y_train)
print("Best Parameters:", grid_search.best_params_)
print("Best CV R²:", grid_search.best_score_)

In [ ]:
best_model = grid_search.best_estimator_
Y_pred = best_model.predict(X_test)

In [ ]:
mae = mean_absolute_error(Y_test, Y_pred)
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
r2 = r2_score(Y_test, Y_pred)
print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

In [ ]:
new_house = pd.DataFrame({
    "mahalle": ["شهرک ولیعصر"],
    "metraj": [100],
    "tedad otagh": [2],
    "tedad servis": [1],
    "parking": [1],
    "anbari": [1],
    "asansor": [1],
    "tabaghe": [2],
    "balkon": [1],
    "kabinet": [1],
    "sal sakht": [1400]
})

In [ ]:
new_house = pd.get_dummies(
    new_house,
    columns=["mahalle"],
    dtype=int
)

In [ ]:
new_house = new_house.reindex(
    columns=X.columns,
    fill_value=0
)

In [ ]:
new_house = imputer.transform(new_house)

In [ ]:
prediction = best_model.predict(new_house)

In [ ]:
prediction_price = scaler_y.inverse_transform(
    prediction.reshape(-1, 1)
).ravel()

In [37]:
print("قیمت پیش‌بینی‌شده:", prediction_price[0])

قیمت پیش‌بینی‌شده: 6234297619.047619